language: node_js
branches:
  only:
  - master
cache: yarn
install: yarn
script: yarn build-prod
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  fqdn: www.tomruttle.com
  github_token: $GITHUB_TOKEN
