language: node_js
branches:
  only:
  - master
install: npm install
script: npm run build && npm run ci
deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  fqdn: www.tomruttle.com
  github_token: $GITHUB_TOKEN
