// flow-typed signature: c7f5aad2ea387e4346f52cc95596ff5d
// flow-typed version: <<STUB>>/postcss-custom-media_v^6.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-custom-media/index' {
  declare module.exports: $Exports<'postcss-custom-media'>;
}
declare module 'postcss-custom-media/index.js' {
  declare module.exports: $Exports<'postcss-custom-media'>;
}
