// flow-typed signature: 3115e41317bb5969a2ff4c8b77db59d0
// flow-typed version: <<STUB>>/purecss_v^1.0.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purecss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'purecss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purecss/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purecss/index' {
  declare module.exports: $Exports<'purecss'>;
}
declare module 'purecss/index.js' {
  declare module.exports: $Exports<'purecss'>;
}
declare module 'purecss/test/index.js' {
  declare module.exports: $Exports<'purecss/test/index'>;
}
