// flow-typed signature: c1c48c67bbd4bb306416219b3d8f7f41
// flow-typed version: <<STUB>>/purifycss-webpack_v^0.7.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'purifycss-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'purifycss-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'purifycss-webpack/dist/index' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/parse' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/parse.test' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/schema' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/schema.test' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/search' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/search.test' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/validate-options' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/dist/validate-options.test' {
  declare module.exports: any;
}

declare module 'purifycss-webpack/lib/post_install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'purifycss-webpack/dist/index.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/index'>;
}
declare module 'purifycss-webpack/dist/parse.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/parse'>;
}
declare module 'purifycss-webpack/dist/parse.test.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/parse.test'>;
}
declare module 'purifycss-webpack/dist/schema.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/schema'>;
}
declare module 'purifycss-webpack/dist/schema.test.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/schema.test'>;
}
declare module 'purifycss-webpack/dist/search.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/search'>;
}
declare module 'purifycss-webpack/dist/search.test.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/search.test'>;
}
declare module 'purifycss-webpack/dist/validate-options.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/validate-options'>;
}
declare module 'purifycss-webpack/dist/validate-options.test.js' {
  declare module.exports: $Exports<'purifycss-webpack/dist/validate-options.test'>;
}
declare module 'purifycss-webpack/lib/post_install.js' {
  declare module.exports: $Exports<'purifycss-webpack/lib/post_install'>;
}
