// flow-typed signature: 49ae39ce0d764e81381de9425f36f4c0
// flow-typed version: <<STUB>>/static-site-generator-webpack-plugin_v^3.4.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'static-site-generator-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'static-site-generator-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'static-site-generator-webpack-plugin/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'static-site-generator-webpack-plugin/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'static-site-generator-webpack-plugin/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'static-site-generator-webpack-plugin/coverage/lcov-report/prettify'>;
}
declare module 'static-site-generator-webpack-plugin/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'static-site-generator-webpack-plugin/coverage/lcov-report/sorter'>;
}
declare module 'static-site-generator-webpack-plugin/index' {
  declare module.exports: $Exports<'static-site-generator-webpack-plugin'>;
}
declare module 'static-site-generator-webpack-plugin/index.js' {
  declare module.exports: $Exports<'static-site-generator-webpack-plugin'>;
}
