// flow-typed signature: 3b892fb31f879178f50eab2f2a67d0c4
// flow-typed version: <<STUB>>/stylelint-config-css-modules_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-css-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-css-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-css-modules/index' {
  declare module.exports: $Exports<'stylelint-config-css-modules'>;
}
declare module 'stylelint-config-css-modules/index.js' {
  declare module.exports: $Exports<'stylelint-config-css-modules'>;
}
