// flow-typed signature: 3a834e1dc1628a6e8ea3848fb3070c99
// flow-typed version: <<STUB>>/watch-ignore-webpack-plugin_v^1.0.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'watch-ignore-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'watch-ignore-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'watch-ignore-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'watch-ignore-webpack-plugin/test/expected/1/entry' {
  declare module.exports: any;
}

declare module 'watch-ignore-webpack-plugin/test/expected/2/entry' {
  declare module.exports: any;
}

declare module 'watch-ignore-webpack-plugin/test/fixtures/entry' {
  declare module.exports: any;
}

declare module 'watch-ignore-webpack-plugin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'watch-ignore-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'watch-ignore-webpack-plugin/lib/index'>;
}
declare module 'watch-ignore-webpack-plugin/test/expected/1/entry.js' {
  declare module.exports: $Exports<'watch-ignore-webpack-plugin/test/expected/1/entry'>;
}
declare module 'watch-ignore-webpack-plugin/test/expected/2/entry.js' {
  declare module.exports: $Exports<'watch-ignore-webpack-plugin/test/expected/2/entry'>;
}
declare module 'watch-ignore-webpack-plugin/test/fixtures/entry.js' {
  declare module.exports: $Exports<'watch-ignore-webpack-plugin/test/fixtures/entry'>;
}
declare module 'watch-ignore-webpack-plugin/test/index.js' {
  declare module.exports: $Exports<'watch-ignore-webpack-plugin/test/index'>;
}
