// flow-typed signature: 9ac2ec499261f274e18ad79a311a9714
// flow-typed version: <<STUB>>/webpack-cli_v^1.3.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cli/__mocks__/creator/validate-options.mock' {
  declare module.exports: any;
}

declare module 'webpack-cli/__mocks__/inquirer/resolve.mock' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/config-yargs' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/convert-argv' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/process-options' {
  declare module.exports: any;
}

declare module 'webpack-cli/bin/webpack' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/index.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/context/context' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/context/context.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/devtool/__testfixtures__/devtool-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/devtool/__testfixtures__/devtool-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/devtool/devtool' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/devtool/devtool.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/entry/__testfixtures__/entry-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/entry/entry' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/entry/entry.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/externals/__testfixtures__/externals-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/externals/__testfixtures__/externals-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/externals/externals' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/externals/externals.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/module/__testfixtures__/module-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/module/__testfixtures__/module-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/module/module' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/module/module.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/node/__testfixtures__/node-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/node/node' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/node/node.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/__testfixtures__/other-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/amd' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/bail' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/cache' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/merge' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/other.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/other/profile' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/output/__testfixtures__/output-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/output/output' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/output/output.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/performance/__testfixtures__/performance-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/performance/performance' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/performance/performance.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/plugins/__testfixtures__/plugins-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/plugins/plugins' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/plugins/plugins.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/resolve/__testfixtures__/resolve-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/resolve/resolve' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/resolve/resolve.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/stats/__testfixtures__/stats-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/stats/stats' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/stats/stats.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/target/__testfixtures__/target-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/target/__testfixtures__/target-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/target/target' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/target/target.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/top-scope/__testfixtures__/top-scope-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/top-scope/top-scope' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/top-scope/top-scope.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/watch' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/watch.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/watchOptions' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/transformations/watch/watchOptions.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/utils/run-prettier' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/utils/validate-options' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/utils/validate-options.spec' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/utils/entry' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/utils/module' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/utils/plugins' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/utils/tooltip' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/utils/validate' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/webpack-adapter' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/creator/yeoman/webpack-generator' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/initialize' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/migrate' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/__testfixtures__/failing' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/bannerPlugin/bannerPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/bannerPlugin/bannerPlugin.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/defineTest' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/extractTextPlugin/__testfixtures__/extractTextPlugin.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/extractTextPlugin/extractTextPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/extractTextPlugin/extractTextPlugin.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/index' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/index.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-3.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-3.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-4.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-5.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-6.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/loaders' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/loaders/loaders.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/outputPath/outputPath' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/outputPath/outputPath.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-3.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-4.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-3.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeJsonLoader/removeJsonLoader' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/removeJsonLoader/removeJsonLoader.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/resolve/__testfixtures__/resolve.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/resolve/resolve' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/resolve/resolve.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-0.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-1.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-2.input' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/uglifyJsPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/uglifyJsPlugin.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/utils' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/transformations/utils.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/npm-exists' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/npm-exists.spec' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/npm-packages-exists' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/resolve-packages' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/resolve-packages.spec' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/validateSchema' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/WebpackOptionsValidationError' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cli/__mocks__/creator/validate-options.mock.js' {
  declare module.exports: $Exports<'webpack-cli/__mocks__/creator/validate-options.mock'>;
}
declare module 'webpack-cli/__mocks__/inquirer/resolve.mock.js' {
  declare module.exports: $Exports<'webpack-cli/__mocks__/inquirer/resolve.mock'>;
}
declare module 'webpack-cli/bin/config-yargs.js' {
  declare module.exports: $Exports<'webpack-cli/bin/config-yargs'>;
}
declare module 'webpack-cli/bin/convert-argv.js' {
  declare module.exports: $Exports<'webpack-cli/bin/convert-argv'>;
}
declare module 'webpack-cli/bin/process-options.js' {
  declare module.exports: $Exports<'webpack-cli/bin/process-options'>;
}
declare module 'webpack-cli/bin/webpack.js' {
  declare module.exports: $Exports<'webpack-cli/bin/webpack'>;
}
declare module 'webpack-cli/lib/creator/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/index'>;
}
declare module 'webpack-cli/lib/creator/index.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/index.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-1.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/context/__testfixtures__/context-2.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/context/context.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/context/context'>;
}
declare module 'webpack-cli/lib/creator/transformations/context/context.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/context/context.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/devtool/__testfixtures__/devtool-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/devtool/__testfixtures__/devtool-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/devtool/__testfixtures__/devtool-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/devtool/__testfixtures__/devtool-1.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/devtool/devtool.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/devtool/devtool'>;
}
declare module 'webpack-cli/lib/creator/transformations/devtool/devtool.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/devtool/devtool.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/entry/__testfixtures__/entry-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/entry/__testfixtures__/entry-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/entry/entry.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/entry/entry'>;
}
declare module 'webpack-cli/lib/creator/transformations/entry/entry.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/entry/entry.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/externals/__testfixtures__/externals-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/externals/__testfixtures__/externals-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/externals/__testfixtures__/externals-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/externals/__testfixtures__/externals-1.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/externals/externals.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/externals/externals'>;
}
declare module 'webpack-cli/lib/creator/transformations/externals/externals.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/externals/externals.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/index'>;
}
declare module 'webpack-cli/lib/creator/transformations/module/__testfixtures__/module-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/module/__testfixtures__/module-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/module/__testfixtures__/module-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/module/__testfixtures__/module-1.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/module/module.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/module/module'>;
}
declare module 'webpack-cli/lib/creator/transformations/module/module.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/module/module.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/node/__testfixtures__/node-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/node/__testfixtures__/node-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/node/node.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/node/node'>;
}
declare module 'webpack-cli/lib/creator/transformations/node/node.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/node/node.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/__testfixtures__/other-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/__testfixtures__/other-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/amd.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/amd'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/bail.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/bail'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/cache.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/cache'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/merge.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/merge'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/other.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/other.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/other/profile.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/other/profile'>;
}
declare module 'webpack-cli/lib/creator/transformations/output/__testfixtures__/output-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/output/__testfixtures__/output-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/output/output.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/output/output'>;
}
declare module 'webpack-cli/lib/creator/transformations/output/output.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/output/output.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/performance/__testfixtures__/performance-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/performance/__testfixtures__/performance-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/performance/performance.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/performance/performance'>;
}
declare module 'webpack-cli/lib/creator/transformations/performance/performance.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/performance/performance.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/plugins/__testfixtures__/plugins-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/plugins/__testfixtures__/plugins-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/plugins/plugins.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/plugins/plugins'>;
}
declare module 'webpack-cli/lib/creator/transformations/plugins/plugins.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/plugins/plugins.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/resolve/__testfixtures__/resolve-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/resolve/__testfixtures__/resolve-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/resolve/resolve.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/resolve/resolve'>;
}
declare module 'webpack-cli/lib/creator/transformations/resolve/resolve.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/resolve/resolve.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/stats/__testfixtures__/stats-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/stats/__testfixtures__/stats-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/stats/stats.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/stats/stats'>;
}
declare module 'webpack-cli/lib/creator/transformations/stats/stats.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/stats/stats.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/target/__testfixtures__/target-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/target/__testfixtures__/target-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/target/__testfixtures__/target-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/target/__testfixtures__/target-1.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/target/target.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/target/target'>;
}
declare module 'webpack-cli/lib/creator/transformations/target/target.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/target/target.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/top-scope/__testfixtures__/top-scope-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/top-scope/__testfixtures__/top-scope-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/top-scope/top-scope.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/top-scope/top-scope'>;
}
declare module 'webpack-cli/lib/creator/transformations/top-scope/top-scope.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/top-scope/top-scope.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-0.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-1.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/__testfixtures__/watch-2.input'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/watch.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/watch'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/watch.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/watch.test'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/watchOptions.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/watchOptions'>;
}
declare module 'webpack-cli/lib/creator/transformations/watch/watchOptions.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/transformations/watch/watchOptions.test'>;
}
declare module 'webpack-cli/lib/creator/utils/run-prettier.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/utils/run-prettier'>;
}
declare module 'webpack-cli/lib/creator/utils/validate-options.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/utils/validate-options'>;
}
declare module 'webpack-cli/lib/creator/utils/validate-options.spec.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/utils/validate-options.spec'>;
}
declare module 'webpack-cli/lib/creator/yeoman/utils/entry.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/utils/entry'>;
}
declare module 'webpack-cli/lib/creator/yeoman/utils/module.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/utils/module'>;
}
declare module 'webpack-cli/lib/creator/yeoman/utils/plugins.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/utils/plugins'>;
}
declare module 'webpack-cli/lib/creator/yeoman/utils/tooltip.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/utils/tooltip'>;
}
declare module 'webpack-cli/lib/creator/yeoman/utils/validate.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/utils/validate'>;
}
declare module 'webpack-cli/lib/creator/yeoman/webpack-adapter.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/webpack-adapter'>;
}
declare module 'webpack-cli/lib/creator/yeoman/webpack-generator.js' {
  declare module.exports: $Exports<'webpack-cli/lib/creator/yeoman/webpack-generator'>;
}
declare module 'webpack-cli/lib/initialize.js' {
  declare module.exports: $Exports<'webpack-cli/lib/initialize'>;
}
declare module 'webpack-cli/lib/migrate.js' {
  declare module.exports: $Exports<'webpack-cli/lib/migrate'>;
}
declare module 'webpack-cli/lib/transformations/__testfixtures__/failing.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/__testfixtures__/failing'>;
}
declare module 'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-0.input'>;
}
declare module 'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-1.input'>;
}
declare module 'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/bannerPlugin/__testfixtures__/bannerPlugin-2.input'>;
}
declare module 'webpack-cli/lib/transformations/bannerPlugin/bannerPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/bannerPlugin/bannerPlugin'>;
}
declare module 'webpack-cli/lib/transformations/bannerPlugin/bannerPlugin.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/bannerPlugin/bannerPlugin.test'>;
}
declare module 'webpack-cli/lib/transformations/defineTest.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/defineTest'>;
}
declare module 'webpack-cli/lib/transformations/extractTextPlugin/__testfixtures__/extractTextPlugin.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/extractTextPlugin/__testfixtures__/extractTextPlugin.input'>;
}
declare module 'webpack-cli/lib/transformations/extractTextPlugin/extractTextPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/extractTextPlugin/extractTextPlugin'>;
}
declare module 'webpack-cli/lib/transformations/extractTextPlugin/extractTextPlugin.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/extractTextPlugin/extractTextPlugin.test'>;
}
declare module 'webpack-cli/lib/transformations/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/index'>;
}
declare module 'webpack-cli/lib/transformations/index.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/index.test'>;
}
declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-0.input'>;
}
declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-1.input'>;
}
declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-2.input'>;
}
declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-3.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaderOptionsPlugin/__testfixtures__/loaderOptionsPlugin-3.input'>;
}
declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin'>;
}
declare module 'webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaderOptionsPlugin/loaderOptionsPlugin.test'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-0.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-1.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-2.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-3.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-3.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-4.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-4.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-5.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-5.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-6.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/__testfixtures__/loaders-6.input'>;
}
declare module 'webpack-cli/lib/transformations/loaders/loaders.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/loaders'>;
}
declare module 'webpack-cli/lib/transformations/loaders/loaders.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/loaders/loaders.test'>;
}
declare module 'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-0.input'>;
}
declare module 'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-1.input'>;
}
declare module 'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/outputPath/__testfixtures__/outputPath-2.input'>;
}
declare module 'webpack-cli/lib/transformations/outputPath/outputPath.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/outputPath/outputPath'>;
}
declare module 'webpack-cli/lib/transformations/outputPath/outputPath.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/outputPath/outputPath.test'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-0.input'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-1.input'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-2.input'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-3.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-3.input'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-4.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/__testfixtures__/removeDeprecatedPlugins-4.input'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins'>;
}
declare module 'webpack-cli/lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeDeprecatedPlugins/removeDeprecatedPlugins.test'>;
}
declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-0.input'>;
}
declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-1.input'>;
}
declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-2.input'>;
}
declare module 'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-3.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeJsonLoader/__testfixtures__/removeJsonLoader-3.input'>;
}
declare module 'webpack-cli/lib/transformations/removeJsonLoader/removeJsonLoader.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeJsonLoader/removeJsonLoader'>;
}
declare module 'webpack-cli/lib/transformations/removeJsonLoader/removeJsonLoader.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/removeJsonLoader/removeJsonLoader.test'>;
}
declare module 'webpack-cli/lib/transformations/resolve/__testfixtures__/resolve.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/resolve/__testfixtures__/resolve.input'>;
}
declare module 'webpack-cli/lib/transformations/resolve/resolve.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/resolve/resolve'>;
}
declare module 'webpack-cli/lib/transformations/resolve/resolve.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/resolve/resolve.test'>;
}
declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-0.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-0.input'>;
}
declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-1.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-1.input'>;
}
declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-2.input.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/uglifyJsPlugin/__testfixtures__/uglifyJsPlugin-2.input'>;
}
declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/uglifyJsPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/uglifyJsPlugin/uglifyJsPlugin'>;
}
declare module 'webpack-cli/lib/transformations/uglifyJsPlugin/uglifyJsPlugin.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/uglifyJsPlugin/uglifyJsPlugin.test'>;
}
declare module 'webpack-cli/lib/transformations/utils.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/utils'>;
}
declare module 'webpack-cli/lib/transformations/utils.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/transformations/utils.test'>;
}
declare module 'webpack-cli/lib/utils/npm-exists.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/npm-exists'>;
}
declare module 'webpack-cli/lib/utils/npm-exists.spec.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/npm-exists.spec'>;
}
declare module 'webpack-cli/lib/utils/npm-packages-exists.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/npm-packages-exists'>;
}
declare module 'webpack-cli/lib/utils/resolve-packages.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/resolve-packages'>;
}
declare module 'webpack-cli/lib/utils/resolve-packages.spec.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/resolve-packages.spec'>;
}
declare module 'webpack-cli/lib/utils/validateSchema.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/validateSchema'>;
}
declare module 'webpack-cli/lib/utils/WebpackOptionsValidationError.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/WebpackOptionsValidationError'>;
}
